image:
  pullPolicy: Always

resources:
  limits:
    memory: 256Mi
    cpu: 100m
  requests:
    memory: 256Mi
    cpu: 100m

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
  