version: '3'

services:
    bot:
        build:
            context: .
            args:
                GOBINARY: arenaBot
                GOFILE: ./bot/bot.go
        container_name: bot
        environment:
            APP_ID: $APP_ID
            GUILD_ID: $GUILD_ID
            BOT_TOKEN: $BOT_TOKEN
            METRICS_PORT: $METRICS_PORT
            ARENA_URL: http://backend:$BACKEND_PORT
        ports:
            - "2113:$METRICS_PORT"
        entrypoint: ["/usr/bin/arenaBot"]
        networks:
            - arenaFront
        restart: always
    backend:
        build:
            context: .
            args:
                GOBINARY: arenaBackend
                GOFILE: ./backend/backend.go
        container_name: backend
        environment:
            MONGO_URL: mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo:27017/$MONGODB_DATABASE?authSource=admin
            HTTP_PORT: $BACKEND_PORT
            METRICS_PORT: $METRICS_PORT
        entrypoint: ["/usr/bin/arenaBackend"]
        ports:
            - "$BACKEND_PORT:$BACKEND_PORT"
            - "$METRICS_PORT:$METRICS_PORT"
        networks:
            - arenaFront
            - arenaBack
        restart: always
    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGODB_ROOT_USER
            MONGO_INITDB_ROOT_PASSWORD: $MONGODB_ROOT_PASSWORD
            MONGODB_INIT_DATABASE: $MONGODB_DATABASE
            MONGODB_USER: $MONGODB_USER
            MONGODB_PASSWORD: $MONGODB_PASSWORD
        networks:
            - arenaBack
            - arenaAdmin
        volumes:
            - ./mongo:/docker-entrypoint-initdb.d/
        restart: always
    mongo-exporter:
        image: bitnami/mongodb-exporter:0.11.2
        container_name: mongo-exporter
        environment:
            MONGODB_URI: mongodb://$MONGODB_ROOT_USER:$MONGODB_ROOT_PASSWORD@mongo:27017/admin
        ports:
            - 9216:9216
        networks:
            - arenaAdmin
    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        environment: 
            ME_CONFIG_MONGODB_URL: mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo:27017/$MONGODB_DATABASE?authSource=admin
        ports:
            - 8081:8081
        networks:
            - arenaAdmin
        depends_on: 
            - mongo
        restart: always

networks:
    arenaFront:
        driver: bridge
    arenaBack:
        driver: bridge
    arenaAdmin:
        driver: bridge

