repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

environments:
  develop:
    values:
    - envs/common.gotmpl
    - envs/develop.gotmpl
  production:
    values:
    - envs/common.gotmpl
    - envs/production.gotmpl

templates:
  default: &default
    chart: ../helm/{{`{{ .Release.Name }}`}}
    namespace: arena
    createNamespace: true
    missingFileHandler: Warn
    values:
      - config/{{`{{ .Release.Name }}`}}/values.yaml
      - config/{{`{{ .Release.Name }}`}}/values.gotmpl
      - config/{{`{{ .Release.Name }}`}}/{{`{{.Environment.Name }}`}}.values.yaml
    secrets:
      - config/{{`{{ .Release.Name }}`}}/{{`{{.Environment.Name }}`}}.secrets.yaml

releases:
- name: bot
  <<: *default
  needs:
    - backend
- name: backend
  <<: *default
  needs:
    - mongo
- name: mongo
  <<: *default
  chart: bitnami/mongodb


