apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }} 
      initContainers:
        - name: "wait-for-service"
          image: busybox
          command: ['sh', '-c', 'echo "Wait for $MONGO_HOST:$MONGO_PORT" ; until nc -zvw 1 $MONGO_HOST $MONGO_PORT; do echo "Waiting for mongodb"; sleep 2 ; done' ]
          env:
          - name: MONGO_HOST
            valueFrom:
              secretKeyRef:
                name: {{ include "backend.fullname" . }}
                key: mongoHost
          - name: MONGO_PORT
            valueFrom:
              secretKeyRef:
                name: {{ include "backend.fullname" . }}
                key: mongoPort
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/arenaBackend"]
          env:
            - name: HTTP_PORT
              value: {{ .Values.http.port }}
            - name: METRICS_PORT
              value: {{ .Values.metrics.port }}
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}
                  key: mongoUri
          ports:
            - name: http
              containerPort: {{ .Values.http.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}