apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  mongoHost: {{ .Values.env.mongoHost | toString | b64enc }}
  mongoPort: {{ .Values.env.mongoPort | toString | b64enc}}
  mongoUri: {{ .Values.env.mongoUri | toString | b64enc }}
