apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  mongoHost: {{ .Values.env.mongo.host | toString | b64enc }}
  mongoPort: {{ .Values.env.mongo.port | toString | b64enc}}
  mongoUri: {{ .Values.env.mongo.uri | toString | b64enc }}
