apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bot.fullname" . }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bot.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/arenaBot"]
          env:
          - name: APP_ID
            value: {{  .Values.env.appID | replace ":" "" | quote }}
          - name: GUILD_ID
            value: {{ .Values.env.guildID | replace ":" "" | quote }}
          - name: ARENA_URL
            value: {{ .Values.env.arenaUrl | quote}}
          - name: BOT_TOKEN
            value: {{ .Values.env.botToken | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
