apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bot.fullname" . }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
type: Opaque
data:
  botToken: {{ .Values.env.botToken | toString | b64enc }}
  arenaUrl: {{ .Values.env.arenaUrl | toString | b64enc }}
  arenaHost: {{ .Values.env.arenaHost | toString | b64enc }}
  arenaPort: {{ .Values.env.arenaPort | toString | b64enc }}
  appID: {{ .Values.env.appID | toString | b64enc }}
  guildID: {{ .Values.env.guildID | toString | b64enc }}
