apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bot.fullname" . }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
type: Opaque
data:
  botToken: {{ .Values.env.botToken | toString | b64enc }}
  arenaUrl: {{ .Values.env.arena.url | toString | b64enc }}
  arenaHost: {{ .Values.env.arena.host | toString | b64enc }}
  arenaPort: {{ .Values.env.arena.port | toString | b64enc }}
  appID: {{ .Values.env.appID | replace ":" "" | b64enc }}
  guildID: {{ .Values.env.guildID | replace ":" "" | b64enc }}
