- name: Check if Helm is installed
  command: "which helm"
  register: helm_installed
  ignore_errors: true

- block:
  - name: "Install Helm GPG key"
    shell: 'curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -'
  
  - name: Install package
    apt:
      name: '{{ package }}'
      state: present
    loop:
      - apt-transport-https
    loop_control:
      loop_var: package

  - name: Add repository
    shell: 'add-apt-repository "deb https://baltocdn.com/helm/stable/debian/ all main"'
  
  - name: Install Helm
    apt:
      name: '{{ package_helm }}'
      state: present
    loop:
      - helm
    loop_control:
      loop_var: package_helm
  when: helm_installed.rc != 0