- name: Remove previous kubeconfig file
  file:
    path: kubeconfig
    state: absent

- name: Read content of k3s.yaml file
  slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_kubeconfig
  tags: kubeconfig

- name: Write kubeconfig to localhost
  copy:
    content: "{{ k3s_kubeconfig['content'] | b64decode }}"
    dest: kubeconfig
  delegate_to: localhost
  tags: kubeconfig

- name: Replace IP address in kubeconfig
  replace:
    path: kubeconfig
    regexp: 'server: https://127.0.0.1:6443'
    replace: 'server: https://{{ inventory_hostname }}:6443'
  delegate_to: localhost
  tags: kubeconfig