name: "Deploy application"

on:
  workflow_run:
    workflows: ["Build Docker images"]
    branches: ["main", "develop"]
    types:
    - completed


env:
  DOCKER_USER: megalooo
  PRIVATE_KEY: vps_key_private
  ANSIBLE_VERSION: "4.3.0"
  HELMFILE_VERSION: v0.140.0

jobs:
  docker-pull:
    name: "Pull docker image"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Pull docker image

  docker-build:
    name: "Build docker image with Ansible"
    runs-on: ubuntu-latest
    needs:
      - docker-pull
    if: needs.docker-pull.result == 'failure'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Ansible Docker image
      run: |-
        cd ansible
        docker build --build-arg ANSIBLE_VERSION=${{ env.ANSIBLE_VERSION }} -t ${{ env.DOCKER_USER }}/ansible:${{ env.ANSIBLE_VERSION }} .
        docker push ${{ env.DOCKER_USER }}/ansible:${{ env.ANSIBLE_VERSION }}

  ansible:
    name: "Prepare environment"
    needs:
      - docker-pull
      - docker-build
    runs-on: ubuntu-latest
    container:
      image: env.DOCKER_USER/ansible:env.ANSIBLE_VERSION
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Decrypt private key
      run: |-
        cd ansible
        echo "${{ secrets.SSH_KEY }}" > $PRIVATE_KEY
        chmod 0600 $PRIVATE_KEY
    - name: Install prerequistes on server
      run: |- 
        cd ansible
        ansible-playbook -e "target=$TARGET_HOST" -e "target_user=$TARGET_USER" -e "private_key=$PRIVATE_KEY" -t remote,k3s,kubectl,helm,kubeconfig playbook.yml
      env:
        TARGET_HOST: ${{ secrets.TARGET_HOST }}
        TARGET_USER: ${{ secrets.TARGET_USER }}
    - name: Upload kubeconfig file
      uses: actions/upload-artifact@v2
      with:
        name: kubeconfig
        path: ansible/kubeconfig
        retention-days: 1
  
  helm:
    name: "Deploy application"
    needs:
      - ansible
    runs-on: ubuntu-latest
    container:
      image: quay.io/roboll/helmfile:helm3-env.HELMFILE_VERSION
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Download kubeconfig file
      uses: actions/download-artifact@v2
      with:
        name: kubeconfig
    - name: Change right on kubeconfig
      run: chmod 0600 kubeconfig
    - name: Install GPG and inject GPG private key
      env:
        PRIVATE_KEY: private.key
      run: |-
        apk add --no-cache --update gnupg
        echo "${{ secrets.PGP_KEY }}" > $PRIVATE_KEY
        gpg --import $PRIVATE_KEY
        rm -f $PRIVATE_KEY
    - name: Run Helmfile - Develop
      if: github.ref != 'refs/heads/main'
      env:
        KUBECONFIG: ../kubeconfig
        ENVIRONMENT: develop
      run: |-
        cd helmfile
        helmfile -e $ENVIRONMENT sync 
    - name: Run Helmfile - Production
      if: github.ref == 'refs/heads/main'
      env:
        KUBECONFIG: ../kubeconfig
        ENVIRONMENT: production
      run: |-
        cd helmfile
        helmfile -e $ENVIRONMENT sync
