name: build-docker-images
on: [push]
jobs:
  build-docker-images:
    - name: Build and push Arena Bot image
      uses: docker/build-push-action@v2.6.1
        build-args:
          GOBINARY: arenaBot
          GOFILE: ./bot/bot.go
        context: ./golang
        push: true
    - name: Build and push Arena Backend image
      uses: docker/build-push-action@v2.6.1
        build-args:
          GOBINARY: arenaBot
          GOFILE: ./bot/bot.go
        context: ./golang
        push: true