name: build-docker-images

on: ["push"]


jobs:
  build_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2.6.1
        build-args:
          GOBINARY: arenaBot
          GOFILE: ./bot/bot.go
        context: ./golang
        push: true

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2.6.1
        build-args:
          GOBINARY: arenaBot
          GOFILE: ./bot/bot.go
        context: ./golang
        push: true