name: Docker Image CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image
      env:
        REPOSITORY: ${{ secrets.DOCKER_USER }}
        IMAGE: idle_arena
        SHA_TAG: ${{ github.sha }}
        TAG: ${{ github.ref }}
      run: |-
        docker build --build-arg GOBINARY=arenaBot --build-arg GOFILE=./bot/bot.go --t $REGISTRY/$IMAGE:$SHA_TAG ./golang
        docker tag $REGISTRY/$IMAGE:$SHA_TAG $REGISTRY/$IMAGE:$TAG
        docker push $REGISTRY/$IMAGE:$SHA_TAG$REGISTRY/$IMAGE:$TAG
